BOOKS_DATABASE_PATH = "../resources/data/books/books.json"
PUBLISHERS_DATABASE_PATH = "../resources/data/publishers/publishers.json"
BOOK_AUTHOR_INDEX = "../resources/data/indexes/BookAuthor.json"
BOOK_ISBN_INDEX = "../resources/data/indexes/BookISBN.json"
BOOK_NAME_INDEX = "../resources/data/indexes/BookTitle.json"
